version: '3.8'

services:
  # MongoDB Service for Catalog
  catalogDB:
    image: mongo
    container_name: catalogDB
    restart: always
    ports:
      - "8000:27017"  # Exposing MongoDB on host port 8000
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db  # Persistent volume for MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dilip123456

  # Redis Service for Basket
  basketDB:
    image: redis
    container_name: basketDB
    restart: always
    ports:
      - "6379:6379"  # Default Redis port
    networks:
      - app-network

  # PostgreSQL for Discount
  discountdb:
    container_name: discountdb
    image: postgres:16.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dilip1234
      - POSTGRES_DB=DiscountDb
    restart: always
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL Admin UI (pgAdmin)
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eCommerce.net
      - PGADMIN_DEFAULT_PASSWORD=dilip1234
    restart: always
    networks:
      - app-network
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  # Catalog API Service
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Service/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - mongoConnection=mongodb://root:dilip123456@catalogDB:27017/?authSource=admin  # MongoDB connection string
    ports:
      - "3000:8080"  # HTTP port
      - "8081:8081"  # HTTPS port
    networks:
      - app-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - catalogDB  # Ensuring MongoDB starts before catalog.api

  # Basket API Service
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Service/Basket/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - redisConnection=basketDB:6379  # Redis connection string
    ports:
      - "3001:8080"  # Exposing Basket API on a different port
      - "8083:8081"
    networks:
      - app-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - basketDB  # Ensuring Redis starts before basket.api

  # Discount API Service
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Service/Discount/Discount.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=dilip1234;"
    ports:
      - "3002:8080"  # Exposing Discount API
      - "8085:8081"
    networks:
      - app-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      discountdb:
        condition: service_healthy  # Ensure DiscountDB is healthy before starting the Discount API

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  postgres_data:
  pgadmin_data:
