services:
  catalogDB:
   image: mongo
   container_name: catalogDB
  
  basketDB:
   image: redis
   container_name: BasketDB

  discountdb:
    image: postgres:16.0
    container_name: discountdb
   
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
 
  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Service/Catalog/Catalog.API/Dockerfile
    
 

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Service/Basket/Basket.API/Dockerfile


  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Service/Discount/Discount.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Service/Ordering/Ordering.api/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3


  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateway/Ocelot.ApiGateway/Dockerfile

