services:
  catalogDB:
   image: mongo
   container_name: catalogDB
  
  basketDB:
   image: redis
   container_name: BasketDB

   
  

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Service/Catalog/Catalog.API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
    
    environment:
    - ASPNETCORE_ENVIRONMENT=Developement
    - ASPNETCORE_HTTP_PORTS=8080
    - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
 


   
  

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Service/Basket/Basket.API/Dockerfile

